version: '3.9'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${db_username}
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_DB=${db_dbname}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - /tmp/redis_data:/var/lib/redis/data
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      # - redis
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/web"]
    restart: always
    # volumes:
    #   - media:/media
    #   - public:/public
  
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - media:/media
  #     - public:/public
  #   depends_on:
  #     - api

  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=a@a.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    expose:
      - 5050
volumes:
  postgres_data:
  # redis_data: